services:
  sentimdb:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:5000"  # change it if port 8080 is unavailable on your machine
    environment:
      - FLASK_APP=app/app.py  
      - FLASK_ENV=development  
    container_name: sentimdb
    restart: unless-stopped 
